### ISSUE TITLE
Name of the function `identicalIEEE`

### ISSUE THREAD

**Issue by asr** [patperry/hs-ieee754#14]
The `identicalIEEE` function on `0.0` and `-0.0` *correctly* returns `False`.

Since IEEE 754 says [1]

>Comparisons shall ignore the sign of zero (so +0 = −0).

 the name 'identicalIEEE' is confusing.

[1] IEEE Computer Society (August 29, 2008). IEEE Standard for Floating-Point Arithmetic".  §5.11, p. 29.

**Comment by patperry** [comment]
My original intention with the name was that `identicalIEEE` tests whether two IEEE floating-point values are bitwise identical. This is different from your interpretation of the name (testing whether two floating-point values are equal according to IEEE comparison conventions). It's unfortunate this is confusing, but changing the name now is not worth breaking backwards compatibility.

**Comment by asr** [comment]
Thanks for the explanation.
