### ISSUE TITLE
please rename nextup*/nextdown*

### ISSUE THREAD

**Issue by clinty** [patperry/hs-ieee754#15]
On unregisterised GHC 8.0, ieee754 fails to build because of prototype mismatch.  https://ghc.haskell.org/trac/ghc/ticket/12802 suggests renaming the functions in cbits/ to not be the same as those in libm.

**Comment by patperry** [comment]
I've renamed the functions, as you suggested. Can you test the latest version to make sure the issue is resolved?

**Comment by clinty** [comment]
Yes, it appears so.

**Comment by patperry** [comment]
Thanks, I just put the new version (0.7.9) on hackage.
