### ISSUE TITLE
What do you think about adding functions like float2word32 to obtain the bit representation

### ISSUE THREAD

**Issue by minad** [patperry/hs-ieee754#17]
This could be done via the FFI or unsafe array casting

**Comment by patperry** [comment]
Not crazy about this idea, mainly because I don’t want to have to deal with endianness headaches.  

Also, there is already a package for serializing and deserializing floats ( https://hackage.haskell.org/package/data-binary-ieee754 ), so I’m not sure what the use case would be.

**Comment by minad** [comment]
Ok, no problem. I thought it could be nice to have everything in one package. But it doesn't really fit into this IEEE typeclass scheme.
