### ISSUE TITLE
Tagging releases on github

### ISSUE THREAD

**Issue by dvc94ch** [patperry/hs-ieee754#18]
Hi,

For distro package maintainers it's nice to be able to quickly find the version of the source that we package from hackage. It's useful for applying bugfixes and security patches if needed. Doing a git blame on the version string doesn't tell us if the next commit is also part of the release without manually checking the changes.

Thank you,
David

**Comment by patperry** [comment]
Thanks for the heads up. I just added a tag for the new version (0.8.0). I'll try to be better about this going forward.
