### ISSUE TITLE
Counterintuitive behavior with `copySign 1.0 nan`

### ISSUE THREAD

**Issue by RyanGlScott** [patperry/hs-ieee754#20]
As the following C program shows, calling `copysign(1.0, ±NAN)` returns `±1.0` depending on the sign bit of the `NAN`:

```c
#include <math.h>
#include <stdio.h>

int main() {
  printf("%f\n", copysign(1.0, +NAN));
  printf("%f\n", copysign(1.0, -NAN));
  return 0;
}
```
```
$ gcc test.c -o test.exe && ./test.exe 
1.000000
-1.000000
```

On the other hand, `ieee754` produces the opposite results:

```
λ> import Numeric.IEEE
λ> copySign 1.0 nan :: Double
-1.0
λ> copySign 1.0 (-nan) :: Double
1.0
```

Is this a bug in `ieee754`'s implementaiton of `copySign`? If not, should this behavior be documented? It certainly went against my expectations.

**Comment by patperry** [comment]
I agree that this seems strange. Maybe it's undefined behavior?

I'm no longer developing this package, but you are welcome to take over as maintainer and fix this issue.

**Comment by RyanGlScott** [comment]
Upon a closer inspection, I don't think this is a bug after all. `ieee754` defines `nan` as:

https://github.com/patperry/hs-ieee754/blob/32ed20b21635e47ce50ffc90e10889f2d6d58caa/Numeric/IEEE.hs#L182

This isn't guaranteed to be the same `NaN` as C's `NAN` macro, as the following program demonstrates:

```c
#include <math.h>
#include <stdio.h>

int main() {
  printf("%f\n", NAN);
  printf("%f\n", 0.0/0.0);
  return 0;
}
```
```
$ gcc test.c -o test.exe && ./test.exe
nan
-nan
```

Sorry for the noise!
