### ISSUE TITLE
package haskell-ieee754 is causing FTBFS of package haskell-hastache on big-endian

### ISSUE THREAD

**Issue by juricast** [patperry/hs-ieee754#5]
Hello,

Package haskell-ieee754 is reason why package haskell-hastache is FTBFS on big-endian.

I have attached a patch for this issue.
With this patch applied to package haskell-ieee754 I was able to build package haskell-hastache on mips big-endian successfully.

haskell-hastache issue:
https://github.com/lymar/hastache/issues/36#

Patch:

<pre>
--- haskell-ieee754-0.7.3.orig/cbits/feqrel_source.c
+++ haskell-ieee754-0.7.3/cbits/feqrel_source.c
@@ -16,7 +16,7 @@
 # define REAL_EXPBIAS            ((uint16_t) 0x3F00)
 # define REAL_EXPBIAS_INT32      ((uint32_t) 0x7F800000)
 # define REAL_MANTISSAMASK_INT32 ((uint32_t) 0x007FFFFF)
-# if BIG_ENDIAN == 1
+# if BYTE_ORDER == BIG_ENDIAN
 #  define REAL_EXPPOS_INT16 0
 # else
 #  define REAL_EXPPOS_INT16 1
@@ -28,7 +28,7 @@
 # define REAL_EXPBIAS            ((uint16_t) 0x3FE0)
 # define REAL_EXPBIAS_INT32      ((uint32_t) 0x7FF00000)
 # define REAL_MANTISSAMASK_INT32 ((uint32_t) 0x000FFFFF); /* for the MSB only */
-# if BIG_ENDIAN == 1
+# if BYTE_ORDER == BIG_ENDIAN
 #  define REAL_EXPPOS_INT16 0
 #  define REAL_SIGNPOS_BYTE 0
 # else
</pre>

Regards,
Jurica

**Comment by patperry** [comment]
Your fix may work for your machine, but now it fails on mine (x86).  I've added a patch with a more robust check (https://github.com/patperry/hs-ieee754/commit/561747ca15dfffe802406606778d080f301ab9f9).  Can you please test this on your big-endian machine?

**Comment by juricast** [comment]
With your patch applied and the package haskell-ieee754 built, I was able to build package haskell-hastache on mips (big-endian) and mipsel (little-endian) successfully.

Regards,
Jurica

**Comment by patperry** [comment]
Thanks for checking!  I just uploaded a new version with the fix to hackage (0.7.5).
