### ISSUE TITLE
Build fails on windows 8.

### ISSUE THREAD

**Issue by kantp** [patperry/hs-ieee754#6]
Hi Patrick,

I just had a build of iee754-0.7.5 fail on a machine running windows 8.  The error message I got was

```
Building ieee754-0.7.5...
Preprocessing library ieee754-0.7.5...
[1 of 2] Compiling Numeric.IEEE     ( Numeric\IEEE.hs, dist\dist-sandbox-d3f7efe0\build\Numeric\IEEE.o )
[2 of 2] Compiling Data.AEq         ( Data\AEq.hs, dist\dist-sandbox-d3f7efe0\build\Data\AEq.o )

In file included from cbits\float.c:16:0:

cbits\feqrel_source.c:27:26:
     fatal error: endian.h: No such file or directory
compilation terminated.
```

Version 0.7.4 builds without problems on the same machine.

I guess this is related to the comment in feqrel_source.c that endian.h is not available on all systems?

Please let me know if you need additional info.

**Comment by patperry** [comment]
Ugh.  Sorry about that.  I just pushed a patch that might fix your problem (https://github.com/patperry/hs-ieee754/commit/cef977a2af7d889c7fedc76475a2025f21c3b1b7 ).  Can you try it and let me know if it works?

**Comment by kantp** [comment]
Yes, that builds just fine!  Thank you!

**Comment by patperry** [comment]
Thanks for reporting and testing.  I just uploaded the new version (0.7.6) to hackage.

**Comment by kantp** [comment]
Tanks for the quick fix!
